[dev]
  command = "npm run vite:start"
  publish = "dist"
  # We need another port for the application because Vite occupies the 3000.
  port = 8080

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200